use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};

#[path = "src/registry_build_support.rs"]
mod registry_build_support;
#[allow(dead_code)]
#[path = "src/strict_json.rs"]
mod strict_json;

use registry_build_support::{collect_registry_files, RegistryScanLimits};

const MAX_REGISTRY_DEPTH: usize = 16;
const MAX_REGISTRY_FILES_PER_KIND: usize = 1_024;

fn main() -> Result<()> {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR is required")?);
    let repository_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .context("sidecar must remain two directories below the repository root")?;
    let canonical_repository_root =
        fs::canonicalize(repository_root).context("canonicalize sidecar repository root")?;
    let output_path = PathBuf::from(env::var_os("OUT_DIR").context("OUT_DIR is required")?)
        .join("channel_event_fixture_registry.rs");

    let registries = [
        RegistryKind {
            constant_name: "EMBEDDED_EVENT_MAPPING_SOURCES",
            root: repository_root.join("fixtures/qiwe/event-mappings"),
            suffix: ".mapping.json",
            max_file_bytes: 128 * 1024,
            max_aggregate_bytes: 16 * 1024 * 1024,
        },
        RegistryKind {
            constant_name: "EMBEDDED_EVENT_FIXTURE_SOURCES",
            root: repository_root.join("fixtures/qiwe/system"),
            suffix: ".fixture.json",
            max_file_bytes: 256 * 1024,
            max_aggregate_bytes: 32 * 1024 * 1024,
        },
        RegistryKind {
            constant_name: "EMBEDDED_EVENT_EXPECTATION_SOURCES",
            root: repository_root.join("fixtures/qiwe/event-mappings"),
            suffix: ".expected.json",
            max_file_bytes: 128 * 1024,
            max_aggregate_bytes: 16 * 1024 * 1024,
        },
        RegistryKind {
            constant_name: "EMBEDDED_RESTRICTED_PRIMITIVE_SOURCES",
            root: repository_root.join("fixtures/qiwe/event-mappings/_primitives"),
            suffix: ".primitive.json",
            max_file_bytes: 64 * 1024,
            max_aggregate_bytes: 4 * 1024 * 1024,
        },
    ];

    let mut generated = String::from("// @generated by runtime/sidecar/build.rs\n");
    for registry in registries {
        println!("cargo:rerun-if-changed={}", registry.root.display());
        let files = collect_registry_files(
            &canonical_repository_root,
            &registry.root,
            registry.suffix,
            RegistryScanLimits {
                max_depth: MAX_REGISTRY_DEPTH,
                max_files: MAX_REGISTRY_FILES_PER_KIND,
                max_file_bytes: registry.max_file_bytes,
                max_aggregate_bytes: registry.max_aggregate_bytes,
            },
        )
        .with_context(|| format!("validate {} registry", registry.constant_name))?;

        generated.push_str(&format!(
            "const {}: &[EmbeddedJsonSource] = &[\n",
            registry.constant_name
        ));
        for file in files {
            println!("cargo:rerun-if-changed={}", file.display());
            let relative = repository_relative_path(&canonical_repository_root, &file)?;
            generated.push_str(&format!(
                "    EmbeddedJsonSource {{ path: {relative:?}, contents: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../\", {relative:?})) }},\n"
            ));
        }
        generated.push_str("];\n");
    }

    fs::write(output_path, generated).context("write generated channel-event fixture registry")?;
    Ok(())
}

struct RegistryKind {
    constant_name: &'static str,
    root: PathBuf,
    suffix: &'static str,
    max_file_bytes: usize,
    max_aggregate_bytes: usize,
}

fn repository_relative_path(repository_root: &Path, path: &Path) -> Result<String> {
    let relative = path
        .strip_prefix(repository_root)
        .with_context(|| format!("registry path escaped repository root: {}", path.display()))?;
    relative
        .components()
        .map(|component| {
            component
                .as_os_str()
                .to_str()
                .map(str::to_owned)
                .with_context(|| format!("registry path must be UTF-8: {}", path.display()))
        })
        .collect::<Result<Vec<_>>>()
        .map(|components| components.join("/"))
}
